### ISSUE TITLE
WebEngagePlugin$1.run

### ISSUE THREAD

**Issue by moreirawebmaster** [WebEngage/webengage-flutter#40]
Hello.

Version plugin: webengage_flutter: 1.2.4

My app conttains this error:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
       at com.webengage.webengage_plugin.WebEngagePlugin$1.run(WebEngagePlugin.java:406)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:223)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:7942)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by MilindWebEngage** [comment]
@moreirawebmaster Can you explain when you are getting this error? (Is it on app start, Is it a recurring error or not, and are there specific steps to reproduce it?)

**Comment by moreirawebmaster** [comment]
Hi @MilindWebEngage this error is recurring in start app. My firebase crashlyttics catch to many erros how it.

**Comment by MilindWebEngage** [comment]
@moreirawebmaster Please raise a ticket at [support@webengage.com](mailto:support@webengage.com) for the same. Share the integration screenshot and the app for testing so that we can determine the exact cause of the issue.

**Comment by manish-cashify** [comment]
@moreirawebmaster any update on this issue? Same issue is reported on crashlytics dashboard.

**Comment by Rohit-joshi-apna** [comment]
Getting the same error on crashlytics.

**Comment by MilindWebEngage** [comment]
@Rohit-joshi-apna We have fixed this issue in the latest version 1.3.0. Please upgrade to the latest version.
